title: 可
language: zh_cn #默认是中文

menus:
    main:
    - Home: /2020010501.markdown
    - Archives: /archives/2020010501
    - About: /about/2020010501.markdown
    side:
    - Categories: /categories/
    - Tags: /tags/
